version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-back
    image: drvetall/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    image: drvetall/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    container_name: nginx
    image: drvetall/foodgram_nginx
    ports:
      - "7500:80"
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
    

